### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by KoichiHashikawa** [aertslab/SCopeLoomR#1]
When installing, I have following errors and failed.

Downloading GitHub repo aertslab/SCopeLoomR@master
from URL https://api.github.com/repos/aertslab/SCopeLoomR/zipball/master
Installing SCopeLoomR
Installing 1 package: rjson
Warning message:
"unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5/PACKAGES'"

**Comment by KoichiHashikawa** [comment]
Also 
I failed to install HDF5 with following errors
Error in parse(text = x, srcfile = src): <text>:1:6: unexpected symbol
1: wget https
         ^
Traceback:

**Comment by dweemx** [comment]
Installing HDF5 the way it's described in the README.md is not going to work for Windows.
Try to install HDF5 using prebuilt libraries available at https://www.hdfgroup.org/downloads/hdf5/.

**Comment by KoichiHashikawa** [comment]
Thanks. 
Also, doMC cannot be installed may be also because I am using Windows.

Does subsequent analysis depend on doMC or if there are any substitution?

**Comment by KoichiHashikawa** [comment]
I tried Mac computer, but saw an error.
Error in parse(text = x, srcfile = src): <text>:1:6: unexpected symbol
1: wget https
         ^
Traceback:

**Comment by dweemx** [comment]
- `wget` is not going to work neither on Mac OS except if you have installed it (see https://www.mkyong.com/mac/wget-on-mac-os-x/).

I have updated the README.md to use `curl` which should be compatible by default on Linux and MacOS machines.
- Indeed `doMC` does not work for Windows and it is not required by `SCopeLoomR` so you can omit its installation.

**Comment by KoichiHashikawa** [comment]
1. About hdf5, is hdf5r sufficient?
2. Installation error for aertslab/SCopeLoomR partially come from the lastest version of R.
After reinstall older version (R3.4.3), the install_github("aertslab/SCopeLoomR") started to run, but caused error because of existing Rcpp package. 
In addition, for some reason, install_github("aertslab/SCopeLoomR") crashed R and I reinstalled, R and anaconda again.
It might help if I can install SCopeLoomR without installing Rcpp.
Do you have advice?

**Comment by dweemx** [comment]
1. The R package `hdf5r` requires HDF5 library to be installed. So if you can install the R package correctly, then it should be fine. 
2.  I don't follow you. Could you post the steps and the stack trace showing clearly the error you get?

**Comment by KoichiHashikawa** [comment]
The problem seems that installation causes corruption in some packages that I already installed via installation of Seurat.
1. Before installation of SCopeLoomR and SCENIC
packageVersion("Rtsne")
packageVersion("mixtools")
packageVersion("Rcpp")
gives
[1] '0.15'

[1] '1.1.0'

[1] '0.12.18'

2. biocLite(c("GENIE3", "RcisTarget", "AUCell")) caused no issue
3. biocLite(c("mixtools")). caused issue on mixtools
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.7 (BiocInstaller 1.30.0), R 3.5.1 (2018-07-02).
Installing package(s) 'mixtools'

package 'mixtools' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'mixtools'"

and 
packageVersion("mixtools") 
gives
Error in packageVersion("mixtools"): package 'mixtools' not found

4. biocLite(c("NMF", "Rtsne", "R2HTML")) caused issue on Rtsne

BioC_mirror: https://bioconductor.org
Using Bioconductor 3.7 (BiocInstaller 1.30.0), R 3.5.1 (2018-07-02).
Installing package(s) 'NMF', 'Rtsne', 'R2HTML'

package 'NMF' successfully unpacked and MD5 sums checked
package 'Rtsne' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'Rtsne'"

package 'R2HTML' successfully unpacked and MD5 sums checked

and
packageVersion( "Rtsne")
gives
Error in packageVersion("Rtsne"): package 'Rtsne' not found

5. install_github("aertslab/SCopeLoomR",repos=c(CRAN="https://cran.cnr.berkeley.edu/")) caused issue on Rcpp

Downloading GitHub repo aertslab/SCopeLoomR@master

Rcpp  (NA -> 1.0.0  ) [CRAN]
rjson (NA -> 0.2.20 ) [CRAN]
rlist (NA -> 0.4.6.1) [CRAN]

Installing 3 packages: Rcpp, rjson, rlist

package 'Rcpp' successfully unpacked and MD5 sums checked

Error: (converted from warning) cannot remove prior installation of package 'Rcpp'
Traceback:
1. install_github("aertslab/SCopeLoomR", repos = c(CRAN = "https://cran.cnr.berkeley.edu/"))
2. install_remotes(remotes, auth_token = auth_token, host = host, 
 .     dependencies = dependencies, upgrade = upgrade, force = force, 
 .     quiet = quiet, build = build, build_opts = build_opts, repos = repos, 
 .     type = type, ...)
3. vapply(remotes, install_remote, ..., FUN.VALUE = character(1))
4. FUN(X[[i]], ...)
5. install(source, dependencies = dependencies, upgrade = upgrade, 
 .     force = force, quiet = quiet, build = build, build_opts = build_opts, 
 .     repos = repos, type = type, ...)
6. install_deps(pkgdir, dependencies = dependencies, quiet = quiet, 
 .     build = build, build_opts = build_opts, upgrade = upgrade, 
 .     repos = repos, type = type, ...)
7. update(packages, dependencies = dep_deps, quiet = quiet, upgrade = upgrade, 
 .     build = build, build_opts = build_opts, ...)
8. update.package_deps(packages, dependencies = dep_deps, quiet = quiet, 
 .     upgrade = upgrade, build = build, build_opts = build_opts, 
 .     ...)
9. install_packages(object$package[object$is_cran & behind], repos = attr(object, 
 .     "repos"), type = attr(object, "type"), dependencies = dependencies, 
 .     quiet = quiet, ...)
10. do.call(safe_install_packages, c(list(packages, repos = repos, 
  .     type = type, dependencies = dependencies, quiet = quiet), 
  .     args))
11. (function (...) 
  . {
  .     lib <- paste(.libPaths(), collapse = ":")
  .     if (has_package("crancache") && has_package("callr")) {
  .         i.p <- "crancache" %::% "install_packages"
  .     }
  .     else {
  .         i.p <- utils::install.packages
  .     }
  .     with_envvar(c(R_LIBS = lib, R_LIBS_USER = lib, R_LIBS_SITE = lib), 
  .         if (should_error_for_warnings()) {
  .             with_options(list(warn = 2), with_rprofile_user("options(warn = 2)", 
  .                 i.p(...)))
  .         }
  .         else {
  .             i.p(...)
  .         })
  . })(c("Rcpp", "rjson", "rlist"), repos = c(CRAN = "https://cran.cnr.berkeley.edu/"), 
  .     type = "both", dependencies = NA, quiet = FALSE)
12. with_envvar(c(R_LIBS = lib, R_LIBS_USER = lib, R_LIBS_SITE = lib), 
  .     if (should_error_for_warnings()) {
  .         with_options(list(warn = 2), with_rprofile_user("options(warn = 2)", 
  .             i.p(...)))
  .     } else {
  .         i.p(...)
  .     })
13. force(code)
14. with_options(list(warn = 2), with_rprofile_user("options(warn = 2)", 
  .     i.p(...)))
15. force(code)
16. with_rprofile_user("options(warn = 2)", i.p(...))
17. with_envvar(c(R_PROFILE_USER = temp_rprofile), {
  .     force(code)
  . })
18. force(code)
19. force(code)
20. i.p(...)
21. .install.winbinary(pkgs = bins, lib = lib, contriburl = contrib.url(repos, 
  .     type2), method = method, available = av2, destdir = destdir, 
  .     dependencies = NULL, libs_only = libs_only, quiet = quiet, 
  .     ...)
22. unpackPkgZip(foundpkgs[okp, 2L], foundpkgs[okp, 1L], lib, libs_only, 
  .     lock)
23. warning(gettextf("cannot remove prior installation of package %s", 
  .     sQuote(pkgname)), domain = NA, call. = FALSE, immediate. = TRUE)
24. .signalSimpleWarning("cannot remove prior installation of package 'Rcpp'", 
  .     quote(NULL))
25. withRestarts({
  .     .Internal(.signalCondition(simpleWarning(msg, call), msg, 
  .         call))
  .     .Internal(.dfltWarn(msg, call))
  . }, muffleWarning = function() NULL)
26. withOneRestart(expr, restarts[[1L]])
27. doWithOneRestart(return(expr), restart)

and now
packageVersion("Rcpp")
gives
Error in packageVersion("Rcpp"): package 'Rcpp' not found
Traceback:
6. corruption of Rcpp caused malfunction of R in jupyternotebook
I need to reinstall everything to fix this.

7. Can you really successfully install SCopeLoomR and SCENIC on PC of windows 10?

thanks for reading this long comment!

**Comment by dweemx** [comment]
I will have to test this on a Windows machine to try to reproduce your error. Meanwhile, I would consider to check this post https://stackoverflow.com/questions/26570912/error-in-installation-a-r-package. This could potentially solve the multiple "cannot remove prior installation of package 'X'" issues you encounter.

**Comment by KoichiHashikawa** [comment]
Thanks for the advice.
In addition, I used my Mac computer to install ScopeLoomR, but got the following error.

Downloading GitHub repo aertslab/SCopeLoomR@master
from URL https://api.github.com/repos/aertslab/SCopeLoomR/zipball/master
Installing SCopeLoomR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/hd/jfvg2qw96kn9xd2bqqjjshhm0000gn/T/RtmpqdHEzT/devtools10f0b225a9501/aertslab-SCopeLoomR-b999d1e'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library'  \
  --install-tests

**Comment by dweemx** [comment]
> Downloading GitHub repo aertslab/SCopeLoomR@master
> from URL https://api.github.com/repos/aertslab/SCopeLoomR/zipball/master
> Installing SCopeLoomR
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ 
> --no-save --no-restore --quiet CMD INSTALL 
> '/private/var/folders/hd/jfvg2qw96kn9xd2bqqjjshhm0000gn/T/RtmpqdHEzT/devtools10f0b225a9501/aertslab-SCopeLoomR-b999d1e' 
> --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library' 
> --install-tests

This doesn't seem to be an error...

**Comment by KoichiHashikawa** [comment]
packageVersion("aertslab/SCopeLoomR")
gives
Error in packageVersion("aertslab/SCopeLoomR"): package ‘aertslab/SCopeLoomR’ not found

Seems to be common errors such as in https://github.com/catavallejos/BASiCS/issues/9

My colleague also failed to install SCopeLoomR and SCENIC.

**Comment by dweemx** [comment]
`packageVersion("aertslab/SCopeLoomR")` is not going to work. You should do `packageVersion("SCopeLoomR")`

**Comment by dweemx** [comment]
There's been an issue regarding installation of `SCopeLoomR` in a recent post. Maybe try this to install `SCopeLoomR` like this:
```
install_github("aertslab/SCopeLoomR", repos = c(CRAN = "https://cran.cnr.berkeley.edu/"))
```

Regarding SCENIC, It seems that recent versions of feather is causing some problems on Windows.
Try to install first `feather` (version 0.3.1) using this snippet before installing `SCENIC`:
```
install.packages("https://cran.r-project.org/bin/windows/contrib/3.4/feather_0.3.1.zip", repos=NULL)
```

**Comment by KoichiHashikawa** [comment]
Thanks for the advice.
I now successfully installed ScopeLoomR and SCENIC in the my Mac computer.

But I still had trouble with installing ScopeLoomR (error is "Error: (converted from warning) cannot remove prior installation of package 'Rcpp").
It tries to install Rcpp package that causes crashing my R. If there is a way to install ScopeLoomR without installing Rcpp, it might help.

**Comment by dweemx** [comment]
- `SCopeLoomR` is not dependent on `Rcpp`. I think the problem arise from `devtools` which requires `Rcpp`. Maybe `devtools` wasn't not correctly installed.. Maybe try to remove Rcpp package and devtools and reinstall devtools:
```
remove.packages("devtools)
install.packages("devtools")
devtools::install_github("aertslab/SCopeLoomR")
```
- Another way to install SCopeLoomR is by downloading the binary: https://github.com/aertslab/SCopeLoomR/releases/download/v0.3.1/SCopeLoomR_0.3.1.tar.gz. 
Then in RStudio, you could install it by running:
```
install.packages("SCopeLoomR_0.3.1.tar.gz", repos = NULL, type="source")
```

**Comment by KoichiHashikawa** [comment]
Thanks for the advice!

As you pointed out, it seems that install_github crashes R in my case. (I did not notice this as I used install.packages for most of packages).
Some people also had similar issues https://github.com/r-lib/devtools/issues/524
I tried some of the procedures posted there, but so far I did not have any lucks.

I also tried install.packages("path to the file/SCopeLoomR_0.3.1.tar.gz", repos = NULL, type="source") , but I got 
Warning message in install.packages("F:/UNC/Dropseq/software/test/SCopeLoomR_0.3.1.tar.gz", :
"installation of package 'F:/UNC/Dropseq/software/test/SCopeLoomR_0.3.1.tar.gz' had non-zero exit status"
I looked into this issues, but have not had any luck.

I will use my Mac computer for SCENIC in the mean time to solve this issue.

**Comment by KoichiHashikawa** [comment]
I finally installed ScopeLoomR through
Rcmd INSTALL Desktop/SCopeLoomR_0.3.1.tar.gz
at localhost command window

Do you also have the binary download link for SCENIC? It seems that I do not have luck for SCENIC too from github.
thanks.
