### ISSUE TITLE
could not find function "get_cellAnnotation"

### ISSUE THREAD

**Issue by yingyonghui** [aertslab/SCopeLoomR#10]
After install the package, I ran the command line "cellInfo <- get_cellAnnotation(loom)".
But it showed that "could not find function 'get_cellAnnotation'".
Could anyone help me?
Thanks!

**Comment by dweemx** [comment]
Hi @yingyonghui , 
Did you load the R package ?
```
library(SCopeLoomR)
```
Could you also try to run `?SCopeLoomR::get_cellAnnotation`

**Comment by yingyonghui** [comment]
> Hi @yingyonghui ,
> Did you load the R package ?
> 
> ```
> library(SCopeLoomR)
> ```
> 
> Could you also try to run `?SCopeLoomR::get_cellAnnotation`

Thanks for your reply @mase5 ,
I followed the instruction in [https://rawcdn.githack.com/aertslab/SCENIC/0a4c96ed8d930edd8868f07428090f9dae264705/inst/doc/SCENIC_Running.html]
After loading the package and running the command line "get_cellAnnotation(loom)", it ended up with the errors above.
I tried ?SCopeLoomR::get_cellAnnotation, but it showed that "No documentation for ‘get_cellAnnotation’ ...", just as the following:

>library(SCopeLoomR)

Attaching package: ‘SCopeLoomR’

The following object is masked from ‘package:base’:

    flush

>?SCopeLoomR::get_cellAnnotation
No documentation for ‘get_cellAnnotation’ in specified packages and libraries:
you could try ‘??get_cellAnnotation’

**Comment by dweemx** [comment]
Could you tell which version of SCopeLoomR you have installed ? 
You can know this by running `packageVersion("SCopeLoomR")`

**Comment by yingyonghui** [comment]
> Could you tell which version of SCopeLoomR you have installed ?
> You can know this by running `packageVersion("SCopeLoomR")`

It shows that the version of SCopeLoomR is 0.3.1.
And the version of R is 3.5.1, in an Ubuntu 18.04 platform.
Thanks.

**Comment by yingyonghui** [comment]
> > Could you tell which version of SCopeLoomR you have installed ?
> > You can know this by running `packageVersion("SCopeLoomR")`
> 
> It shows that the version of SCopeLoomR is 0.3.1.
> And the version of R is 3.5.1, in an Ubuntu 18.04 platform.
> Thanks.

I reinstalled SCopeLoomR of version 0.5.0, and  it works correctly now.
Thanks for your reminder!
I think this issue could be closed now.

**Comment by yuyingrong** [comment]
Just in case someone wonders: 
I am using SCopeLoomR v.0.13.0, but got the same issue: could not find function "get_cellAnnotation".
Then I found that the function now goes by: get_cell_annotation().

**Comment by yanpinlu** [comment]
> Just in case someone wonders: I am using SCopeLoomR v.0.13.0, but got the same issue: could not find function "get_cellAnnotation". Then I found that the function now goes by: get_cell_annotation().
I am using ScopeLoomR v.0.13.0, the same problem you have, can you use it now? How to solve this problem

**Comment by yanpinlu** [comment]
I am using ScopeLoomR v.0.13.0, the same problem you have, can you use it now? How to solve this problem @yuyingrong @dweemx

**Comment by s-aibar** [comment]
Hello,

The function has been renamed to `get_cell_annotation`

( https://github.com/aertslab/SCopeLoomR/blob/99726f5f7da794042036b73924b6a10d6e7b4d5d/README.md)
