### ISSUE TITLE
What do superposition OR AND mean in SCope Compare part? 

### ISSUE THREAD

**Issue by sygongcode** [aertslab/SCopeLoomR#19]
Hello, everyone,

First, thank you for your nice work that helps me a lot with my project.

I have some questions when I using SCope to search for some genes' alteration in the fly brain in aging. I didn't find any contact information for help. So, I come here to ask for help. 
The question is that when I use the compare part, I found three options, Number of displays, Superposition(N/A, OR, AND), and Configuration, what is the exact mean of superposition? For example, If I drag age 3, and age 15, age 30 and age 50 in genotype W1118, male fly brain for comparison. And then I type a gene that I am interested in. after  I select OR or AND in the superposition option, I got different plots. So, what are the exact means when I select OR or AND? Can anyone help me? Thank you.

Best regards,

Shangyu

**Comment by dweemx** [comment]
Hi @sygongcode ,
Thanks for your feedback.
Your request is related to SCope (visualization tool) and not to SCopeLoomR (R package to build loom files).
Therefore, could you please close this issue and create a new one at https://github.com/aertslab/SCope ?

**Comment by sygongcode** [comment]
> Hi @sygongcode ,
> Thanks for your feedback.
> Your request is related to SCope (visualization tool) and not to SCopeLoomR (R package to build loom files).
> Therefore, could you please close this issue and create a new one at https://github.com/aertslab/SCope ?

Ok, I am sorry. I will close it. Thank you
