### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by abhisheksinghnl** [aertslab/SCopeLoomR#2]
Hi,

I am working on aws and I was trying to install the package. I followed everything as mentioned in the installation steps. I get the following error on the last step:

```
> install_github("aertslab/SCopeLoomR")
Downloading GitHub repo aertslab/SCopeLoomR@master
Installing 2 packages: hdf5r, rlist
Installing packages into ‘/home/asingh74/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
Error: (converted from warning) unable to access index for repository http://www.bioconductor.org/packages/3.6/extra/src/contrib:
  cannot open URL 'http://www.bioconductor.org/packages/3.6/extra/src/contrib/PACKAGES'
```

How can I fix this error? Please let me now.

**Comment by dweemx** [comment]
Which R version are you running?

**Comment by abhisheksinghnl** [comment]
R 3.4.2

**Comment by dweemx** [comment]
I don't know why it's trying to accessing BioC extra page from Bioconductor 3.6 which is weird because it has been removed from this version. 
Maybe try to reinstall Bioconductor?

**Comment by abhisheksinghnl** [comment]
The new BiocManager is available for R3.5 version, till 3.4 biocLite was used. If that is what the problem is?

**Comment by abhisheksinghnl** [comment]
I solved it by installing it like this

install_github("aertslab/SCopeLoomR", repos = c(CRAN = "https://cran.cnr.berkeley.edu/"))

**Comment by dweemx** [comment]
Great!
