### ISSUE TITLE
build_loom function error

### ISSUE THREAD

**Issue by hzongyao** [aertslab/SCopeLoomR#25]
I am using `loom <- build_loom(output, dgem=exprMat)` function, but ,there is an error as follows: Error in eval(x[[i]], envir = envir) : object 'row.start' not found. and I wonder where can I find the 0.9 version？ thank you！

**Comment by dweemx** [comment]
Hi @hzongyao ,
Should be fixed in `master`. 
(A reinstall of the package is required)
