### ISSUE TITLE
Inconsistency between get_ and add_ regulons (AUC)

### ISSUE THREAD

**Issue by s-aibar** [aertslab/SCopeLoomR#27]
`get_regulons_AUC` is not able to read the matrix written by `add_scenic_regulons_auc_matrix`.

I think the problem is that `get_regulons_AUC` uses the argument `column.attr.name="MotifRegulonsAUC"`,
while `add_scenic_regulons_auc_matrix` uses a global attribute : 
```add_col_attr(
    loom = loom,
    key = CA_REGULONS_AUC,
    value = as.data.frame(x = t(x = regulons.AUC))
  )
```

(By the way, it could be good to add an alias to keep both names consistent. i.e. 
`add_regulons_AUC <- add_scenic_regulons_auc_matrix <- function() ...` )

**Comment by dweemx** [comment]
Fix in e193e154de5d8d8d72c87da14ee3a5f51715d22e
