### ISSUE TITLE
Link to a rendered version of the vignette & vignette version

### ISSUE THREAD

**Issue by cflerin** [aertslab/SCopeLoomR#34]
Hi @dweemx et al.,

It would be nice to have a rendered version of the vignette available. When I click the link from the main readme it just takes me to the raw code.

One possibility is to generate the html (I see this is already done in `vignettes/`) and use html preview:
http://htmlpreview.github.io/?https://github.com/aertslab/SCopeLoomR/blob/master/vignettes/SCopeLoomR_tutorial.nb.html

Another thing I noticed in the tutorial: `HTML built on Dec 01, 2019 with SCopeLoomR version 0.5.0.`, but the current version is v0.10.4. Is the tutorial current?

**Comment by dweemx** [comment]
Thanks @cflerin,
I will rebuild the tutorial and add a link with html preview to the `README.md`

**Comment by cflerin** [comment]
Thanks @dweemx !
