### ISSUE TITLE
adding metadata to loom files

### ISSUE THREAD

**Issue by abhisheksinghnl** [aertslab/SCopeLoomR#5]
Hi,

I am able to generate loom files using following code:

```
file.name <- "example.loom"
loom <- build_loom(file.name=file.name,
                   dgem=dgem,
                   title="Fake expression dataset for examples",
                   genome="Mouse", # Just for user information, not used internally
                   default.embedding=default.tsne,
                   default.embedding.name=default.tne.name)
```

However, when I upload these files in SCOPE, I get empty metadata columns. How can I add, say, gene expression to this loom file.

Thank you

**Comment by dweemx** [comment]
You should be able to query any gene expression through the gene tab.
Did you finally managed to get it work?

**Comment by abhisheksinghnl** [comment]
Yes, I figured it out. The script will not run without dgem. My fault :(
