### ISSUE TITLE
How to convert the loom file to seurat object?

### ISSUE THREAD

**Issue by Sophia409** [aertslab/SCopeLoomR#9]
I need to merge my seurat data  with the data provided by loom edition(http://mousebrain.org/tissues.html).But I don't know how to convert this loom file to seurat object, so that I can merge them with my own data and do next analysis.
I didn't see this function in your tutorial. I tried to get the matrix and meta data from loom file,and use them to crea tseurat object,but I don't see how to get metadata from loom in your tutorial either.
So what should I do to convert the loom file to seurat object? Can you give me some help?Thank you very much!
Sophia
@tropfenameimer @ghuls @KrisDavie @cflerin @sedjro

**Comment by dweemx** [comment]
Hi @Sophia409,
Currently, there is no implemented function in `SCopeLoomR` to convert a loom to Seurat however you should be able to do this with `loomR` (see https://satijalab.org/loomR/loomR_tutorial.html, section `Creating a loom object from a Seurat object (converting between Seurat and loom)`)

**Comment by Sophia409** [comment]
Thank you!But [the tutorial]( https://satijalab.org/loomR/loomR_tutorial.html) says that : Seurat offers a conversion function to go from Seurat objects to loom files. The reverse conversion is currently in progress.
Does it means that I could't convert loom file to seurat?So what should I do to convert the loom file to my seurat object? Or how to merge loom file with my seurat object?Can you give me some help?Thank you very much!
![default](https://user-images.githubusercontent.com/30619010/54024634-4d29ca00-41d3-11e9-84a5-85a9fd246526.png)
@mase5

**Comment by dweemx** [comment]
You could try [`sceasy`](https://github.com/cellgeni/sceasy) + `Seurat::ReadH5AD`

**Comment by dweemx** [comment]
Considering this as a closed issue
